spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true  # Habilita o console do H2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
