spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nome_do_banco
    driver-class-name: org.postgresql.Driver
    username: seu_usuario
    password: sua_senha
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
